### ISSUE TITLE
[Add]: a phase

### ISSUE THREAD

**Issue by Jay9874** [BIT-GDSC/Resources#1]
The phase 4 is as extra but we need a phase for deployment. Rename phase 4 as deployment and add a phase 5 for extras in web dev readme.

**Comment by lalshubham** [comment]
@Jay9874 I don't think we should add a new phase coz the deployment part will be done alongside `Framework & Libraries` phase so to get better understanding how this whole process works.
Please *Close* this issue if you found it relevant, otherwise we can give more thought of it.

**Comment by Jay9874** [comment]
Overall who ever sees it will find it more straight way. Framework and library is for writing codes easily and deployment is for making it live.

**Comment by lalshubham** [comment]
Yes, that's right. But to add a new phase entirely for deployment isn't worth. You see in the `Phase 4 - Extras`, I have added those things which might end up being included in first 3 phases. The *npm/yarn* will be covered in `Framework & Libraries`, *appwrite.io* might be covered in the `Databases`, so there's really no need to create individual phases for the tools used in `Extras` phase.

**Comment by Jay9874** [comment]
Deployement dont comes under extra.

**Comment by lalshubham** [comment]
Added this new [Deployment](https://github.com/BIT-GDSC/Resources/commit/862bc9d12887ac81183fb575cb92267bbaae27e2) phase 🙏

**Comment by Jay9874** [comment]
lgtm 👍
